name: Deploy
on:
  push:
    # branches:
    #   - master
jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure pip
        run: pip install pip --upgrade
      - name: Ensure build
        run: pip install build --upgrade
      - name: Ensure twine
        run: pip install twine --upgrade
      - name: Check out repository code
        uses: actions/checkout@v3
      # Calculate version
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      # Build
      # Upload to Pypi through twine
